### ISSUE TITLE
Flutter web build  generating a blank page

### ISSUE THREAD

**Issue by milenafs** [milenafs/todo-list-app#2]
# Problem:
![image](https://github.com/user-attachments/assets/0ff3a923-973c-406f-a2f8-dca374b312da)

**Comment by milenafs** [comment]
# How to fix it
1. generate the web buil: `flutter build web `
2. Chenge the base href from build/web/index.html to:
```html
 <base href="./"> 
```
3. In my deployment workflow, the github page was getting the index from the build/web, but since the build is being generated during deploy and I customized it. I copy the web folder from the build and moved to the root of the project.
4. Change the .yml from the workflow:
```yml
      - name: Deploy to GitHub Pages
        if: matrix.platform == 'web'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web
```
